# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build distribution
        id: build
        run: gradle clean check -PAzureBuildNumber="${{ github.run_id }}"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            gradle-bom/build/test-results/**/*.xml